/**
 * [INPUT]: 依赖 node:test/node:assert 与 tests/helpers/source-test-helpers
 * [OUTPUT]: Kumo md bottom-tabs 护栏测试
 * [POS]: tests/ UI 迁移护栏的底栏导航层，锁定 HomeSettingsPane bottom-tabs 视图拆分、测量链与 skeleton 语义
 * [PROTOCOL]: 变更时更新此头部，然后检查 CLAUDE.md
 */
import { test } from "node:test"
import assert from "node:assert/strict"
import { assertNamedImports, readSource } from "./helpers/source-test-helpers.js"

test("HomeSettingsPane splits md drawer-open bottom-tabs layout from grid layout", () => {
  const paneSource = readSource("src/pages/registry/sections/workspace/HomeSettingsPane.jsx")
  const bottomTabsSource = readSource("src/pages/registry/sections/workspace/HomeSettingsPaneBottomTabsLayout.jsx")

  assert.match(paneSource, /import \{ useState \} from "react"/)
  assert.match(paneSource, /import \{ HomeSettingsPaneBottomTabsLayout \} from "\.\/HomeSettingsPaneBottomTabsLayout"/)
  assert.match(paneSource, /useSegmentedWorkspaceLayout = false/)
  assert.match(paneSource, /const \[activeTabId, setActiveTabId\] = useState\(null\)/)
  assert.match(paneSource, /const MD_BOTTOM_TABS_EMPTY_STATE_CARD_IDS = \["location", "wallpaper-lang", "goal-fields", "colors", "device", "url"\]/)
  assert.match(paneSource, /const MD_BOTTOM_TABS_SLOT_COUNT = 6/)
  assert.match(paneSource, /const MID_SKELETON_ROW_COUNT = MD_BOTTOM_TABS_SLOT_COUNT/)
  assert.match(paneSource, /function resolveMdBottomTabsCardOrder\(selectedType\)/)
  assert.match(paneSource, /function resolveMdBottomTabsRevealedCardIds\(selectedType, cardOrder, unlockedCount\)/)
  assert.match(paneSource, /const bottomTabsCardOrder = resolveMdBottomTabsCardOrder\(config\.selectedType\)/)
  assert.match(paneSource, /const revealedTabs = resolveMdBottomTabsRevealedCardIds\(config\.selectedType, cardOrder, unlockedCount\)/)
  assert.match(paneSource, /const currentActiveTab = bottomTabsCardOrder\.includes\(activeTabId\) \? activeTabId : bottomTabsCardOrder\[0\]/)
  assert.match(paneSource, /const shouldUseAnchoredSetupRow = effectiveLayoutTier === "mid" \|\| useSegmentedWorkspaceLayout/)
  assert.match(paneSource, /if \(useSegmentedWorkspaceLayout\) return <HomeSettingsPaneBottomTabsLayout/)
  assert.doesNotMatch(paneSource, /function HomeSettingsPaneBottomTabsLayout\(/)
  assert.doesNotMatch(paneSource, /resolveMdBottomTabsActiveTitle/)
  assert.doesNotMatch(paneSource, /resolveMdTabLabel/)
  assert.doesNotMatch(paneSource, /MD_TAB_LABEL_KEY_BY_CARD_ID/)
  assert.doesNotMatch(paneSource, /MD_BOTTOM_TAB_WIDTH_VAR_PREFIX/)
  assert.doesNotMatch(paneSource, /MD_BOTTOM_TAB_MEASURE_TRIGGER_CLASSNAME/)
  assert.doesNotMatch(paneSource, /SettingsTabLabelSkeleton/)
  assert.doesNotMatch(paneSource, /useMdBottomTabsMetrics/)
  assert.doesNotMatch(paneSource, /<Tabs/)
  assert.doesNotMatch(paneSource, /useRef/)

  assertNamedImports(bottomTabsSource, "@/components/ui/kumo", ["Tabs"])
  assert.match(bottomTabsSource, /import \{ useRef \} from "react"/)
  assert.match(bottomTabsSource, /import \{ useMdBottomTabsMetrics \} from "\.\/use-md-bottom-tabs-metrics"/)
  assert.match(bottomTabsSource, /export function HomeSettingsPaneBottomTabsLayout\(/)
  assert.match(bottomTabsSource, /const measureLabels = bottomTabsCardOrder\.map\(\(cardId\) => resolveMdTabLabel\(cardId, t\)\)/)
  assert.match(bottomTabsSource, /const \{ distributedTabWidths, indicatorClassName \} = useMdBottomTabsMetrics\(\{/)
  assert.match(bottomTabsSource, /tabsContainerRef,/)
  assert.match(bottomTabsSource, /measureTriggerRefs,/)
  assert.match(bottomTabsSource, /measureLabels,/)
  assert.match(bottomTabsSource, /const MD_BOTTOM_TAB_WIDTH_VAR_PREFIX = "--md-tab-w-"/)
  assert.match(bottomTabsSource, /const MD_BOTTOM_TAB_MEASURE_TRIGGER_CLASSNAME = "inline-flex items-center rounded-lg px-2.5 text-base whitespace-nowrap"/)
  assert.match(bottomTabsSource, /const MD_BOTTOM_TAB_TRIGGER_CLASSNAMES = \[/)
  assert.match(bottomTabsSource, /"min-w-0 justify-center w-\[var\(--md-tab-w-0\)\] \[flex:0_0_var\(--md-tab-w-0\)\]"/)
  assert.match(bottomTabsSource, /"min-w-0 justify-center w-\[var\(--md-tab-w-5\)\] \[flex:0_0_var\(--md-tab-w-5\)\]"/)
  assert.match(bottomTabsSource, /function resolveMdBottomTabsActiveTitle\(/)
  assert.match(bottomTabsSource, /function resolveMdTabLabel\(cardId, t\)/)
  assert.match(bottomTabsSource, /const MD_TAB_LABEL_KEY_BY_CARD_ID = \{/)
  assert.match(bottomTabsSource, /function resolveMdBottomTabsWidthVars\(widths\)/)
  assert.match(bottomTabsSource, /function resolveMdBottomTabTriggerClassName\(index\)/)
  assert.match(bottomTabsSource, /function resolveMdBottomTabLabelContent\(cardId, isLabelRevealed, t\)/)
  assert.match(bottomTabsSource, /<Tabs/)
  assert.match(bottomTabsSource, /variant="segmented"/)
  assert.match(bottomTabsSource, /listClassName="w-full"/)
  assert.match(bottomTabsSource, /indicatorClassName=\{indicatorClassName\}/)
  assert.match(bottomTabsSource, /tabs=\{bottomTabsCardOrder\.map/)
  assert.match(bottomTabsSource, /label: resolveMdBottomTabLabelContent\(cardId, revealedTabs\.includes\(cardId\), t\)/)
  assert.match(bottomTabsSource, /className: resolveMdBottomTabTriggerClassName\(index\)/)
  assert.match(bottomTabsSource, /data-home-md-bottom-tabs/)
  assert.match(bottomTabsSource, /style=\{bottomTabsWidthVars\}/)
  assert.match(bottomTabsSource, /value=\{currentActiveTab/)
  assert.match(bottomTabsSource, /onValueChange=\{setActiveTabId\}/)
  assert.match(bottomTabsSource, /style=\{\{ height: "var\(--registry-topbar-height\)" \}\}/)
  assert.match(bottomTabsSource, /flex-1 min-h-0/)
  assert.doesNotMatch(bottomTabsSource, /MD_BOTTOM_TABS_SLOT_COUNT/)
  assert.doesNotMatch(bottomTabsSource, /BottomTabsActiveCardPane/)
  assert.doesNotMatch(bottomTabsSource, /BottomTabsTabRail/)
  assert.doesNotMatch(bottomTabsSource, /listClassName="[^"]*bg-transparent/)
  assert.doesNotMatch(bottomTabsSource, /listClassName="[^"]*h-full/)
  assert.doesNotMatch(bottomTabsSource, /listClassName="[^"]*py-1/)
  assert.doesNotMatch(bottomTabsSource, /const tabCount = bottomTabsCardOrder\.length/)
  assert.doesNotMatch(bottomTabsSource, /Array\.from\(\{ length: tabCount \}/)
  assert.doesNotMatch(bottomTabsSource, /w-\[var\(\$\{widthVarName\}\)\]/)
  assert.doesNotMatch(bottomTabsSource, /\[flex:0_0_var\(\$\{widthVarName\}\)\]/)
  assert.doesNotMatch(bottomTabsSource, /className: "min-w-0 basis-0 flex-1/)
  assert.doesNotMatch(bottomTabsSource, /style=\{distributedTabWidths\[index\][\s\S]*width:/)
  assert.doesNotMatch(bottomTabsSource, /const visibleTabs =/)
  assert.doesNotMatch(bottomTabsSource, /useEffect\([\s\S]*setActiveTabId/)
})

test("useMdBottomTabsMetrics owns md bottom-tabs measurement and resize state", () => {
  const source = readSource("src/pages/registry/sections/workspace/use-md-bottom-tabs-metrics.js")

  assert.match(source, /export function useMdBottomTabsMetrics\(\{ tabsContainerRef, measureTriggerRefs, measureLabels \}\)/)
  assert.match(source, /import \{ useLayoutEffect, useRef, useState \} from "react"/)
  assert.match(source, /import \{ resolveMdBottomTabWidths \} from "\.\/md-bottom-tabs-widths"/)
  assert.match(source, /const \[distributedTabWidths, setDistributedTabWidths\] = useState\(\[\]\)/)
  assert.match(source, /const \[isResizingTabs, setIsResizingTabs\] = useState\(false\)/)
  assert.match(source, /const naturalTabWidthsRef = useRef\(\[\]\)/)
  assert.match(source, /const lastTablistWidthRef = useRef\(null\)/)
  assert.match(source, /const resizeSettledTimeoutRef = useRef\(null\)/)
  assert.doesNotMatch(source, /tabCount/)
})

test("useMdBottomTabsMetrics measures synchronously, observes only tablist, and gates indicator transitions", () => {
  const source = readSource("src/pages/registry/sections/workspace/use-md-bottom-tabs-metrics.js")

  assert.match(source, /if \(measureLabels\.length === 0\) \{/)
  assert.match(source, /const measureLabelsKey = measureLabels\.join\("\|"\)/)
  assert.match(source, /const tabsListElement = containerElement\.querySelector\('\[role=\"tablist\"\]'\)/)
  assert.match(source, /const naturalWidths = measureTriggerRefs\.current/)
  assert.match(source, /naturalTabWidthsRef\.current = naturalWidths/)
  assert.match(source, /const tablistWidth = tabsListElement\.getBoundingClientRect\(\)\.width/)
  assert.match(source, /if \(!Number\.isFinite\(tablistWidth\) \|\| tablistWidth <= 0\) return/)
  assert.match(source, /setDistributedTabWidths\(resolveMdBottomTabWidths\(\{/)
  assert.match(source, /naturalWidths: naturalTabWidthsRef\.current/)
  assert.match(source, /if \(typeof document !== "undefined" && document\.fonts && document\.fonts\.status !== "loaded"\) \{/)
  assert.match(source, /document\.fonts\.ready\.then\(\(\) => \{/)
  assert.match(source, /Math\.abs\(nextWidth - lastTablistWidthRef\.current\) <= 1/)
  assert.match(source, /resizeObserver = new ResizeObserver\(\(\) => \{/)
  assert.match(source, /resizeObserver\.observe\(tabsListElement\)/)
  assert.doesNotMatch(source, /resizeObserver\.observe\(containerElement\)/)
  assert.doesNotMatch(source, /new ResizeObserver\(\(\) => \{[\s\S]*measureTriggerRefs\.current/)
  assert.match(source, /resizeSettledTimeoutRef\.current = window\.setTimeout\(\(\) => \{/)
  assert.match(source, /const indicatorClassName = distributedTabWidths\.length !== measureLabels\.length/)
  assert.match(source, /"!opacity-0 !transition-none"/)
  assert.match(source, /: isResizingTabs \? "!transition-none" : undefined/)
  assert.doesNotMatch(source, /requestAnimationFrame/)
})

test("HomeSettingsPane md bottom-tabs keep shell mounted and reveal title-label text independently from card body", () => {
  const paneSource = readSource("src/pages/registry/sections/workspace/HomeSettingsPane.jsx")
  const viewSource = readSource("src/pages/registry/sections/workspace/HomeSettingsPaneBottomTabsLayout.jsx")

  assert.match(paneSource, /const revealedTabs = resolveMdBottomTabsRevealedCardIds\(config\.selectedType, cardOrder, unlockedCount\)/)
  assert.match(paneSource, /const currentActiveTab = bottomTabsCardOrder\.includes\(activeTabId\) \? activeTabId : bottomTabsCardOrder\[0\]/)
  assert.match(paneSource, /const activeCardDefinition = currentActiveTab/)

  assert.match(viewSource, /const isActiveTabRevealed = revealedTabs\.includes\(currentActiveTab\)/)
  assert.match(viewSource, /const activeTitleState = resolveMdBottomTabsActiveTitle\(/)
  assert.match(viewSource, /title=\{activeTitleState\.title\}/)
  assert.match(viewSource, /titleTooltip=\{activeTitleState\.titleTooltip\}/)
  assert.match(viewSource, /isIndexActive=\{activeTitleState\.isIndexActive\}/)
  assert.match(viewSource, /isActiveTabRevealed && activeCardDefinition[\s\S]*?\? activeCardDefinition\.card\.render\(cardViewModel\)\s*:\s*<SettingsCardSkeleton onRequestRevealAll=\{cardViewModel\.config\.selectedType \? onRequestRevealAll : undefined\} \/>/)
  assert.match(viewSource, /if \(!currentActiveTab \|\| !isActiveTabRevealed \|\| !activeCardDefinition\)/)
  assert.match(viewSource, /title: <SettingsCardTitleSkeleton \/>/)
  assert.match(viewSource, /if \(!isLabelRevealed\) return <SettingsTabLabelSkeleton \/>/)
  assert.doesNotMatch(viewSource, /if \(!cardViewModel\.config\.selectedType\) return fallbackGrid/)
})

test("HomeSettingsPane md bottom-tabs empty state uses skeleton title and skeleton tab labels while keeping all slots mounted", () => {
  const source = readSource("src/pages/registry/sections/workspace/HomeSettingsPaneBottomTabsLayout.jsx")

  assert.match(source, /function SettingsTabLabelSkeleton\(\)/)
  assert.match(source, /tabs=\{bottomTabsCardOrder\.map/)
  assert.match(source, /measureLabels = bottomTabsCardOrder\.map/)
  assert.match(source, /revealedTabs\.includes\(cardId\)/)
  assert.match(source, /<SettingsCardTitleSkeleton \/>/)
  assert.match(source, /<SettingsTabLabelSkeleton \/>/)
  assert.match(source, /goal-fields/)
})
